### ISSUE TITLE
Can this be used to calibrate monitors?

### ISSUE THREAD

**Issue by Gil80** [leswright1977/PySpectrometer2#18]
Hi.
I've come across this amazing project by searching for a cheap alternative to spectrometers.
I read that these devices can profile colorimeters and monitors and are better for calibrating monitors than the standard colorimeters.

I'd love to build this but would really like to know if it can be used to calibrate OLED/LCD monitors.

**Comment by leswright1977** [comment]
This is probably not the best tool for this task (at least not in it's current form). The spectral output of monitors can be quite different for example if they are CCFL vs LED for example.
What about the TCS3200/230 Color sensors?

**Comment by ccdunder** [comment]
Hm, I thought it was the other way around: a colorimeter needs calibration profiles, not a spectrometer. In fact, a spectrometer would be much more accurate (theoretically). Would you mind clarifying @leswright1977? It's possible my understanding is flawed and I'd greatly appreciate any pointers so I can course-correct early.

My understanding:
A colorimeter needs calibration profiles for different monitor types in order to compensate for its lack of precision. It measures intensity of a very small number of coarse peaks (e.g. 3 for RGB) and then uses monitor profiles (e.g. CCFL vs LED) to map it's measurements to something more precise (like an SPD). A spectrometer can be used to build such calibration profiles[^1].

It seems to follow that a spectrometer doesn't need these calibration profiles, and could be used in place of a colorimeter. Is there calibration a (Py)spectrometer would need in order to be able to do this (beyond what's described in the guide)?

Thank you in advance for any tips and thank you for creating and sharing such an awesome project with the world.

[^1]: https://www.argyllcms.com/doc/WideGamutColmters.html
